### PR TITLE
[rebased on #232] Support font glyph symbol

### PR DESCRIPTION
**Pull request by marcjansen**
Just a draft PR to see if CI works when the changes from #231 are rebased on top of #232.

### CODE REVIEW

**Comment by marcjansen** [comment]
Looks as if this actually fixes the CI.

**Comment by jahow** [comment]
Looking good indeed! Thanks for taking the time @marcjansen

**Comment by jahow** [comment]
Let me know if you want me to rebase the original PR once #232 is in, or if you'd rather merge this one.

**Comment by marcjansen** [comment]
> Let me know if you want me to rebase the original PR once #232 is in, or if you'd rather merge this one.

Please rebase yours if possible.

**Pull request closed without merging**
